defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/android:api-25-alpha

version: 2
jobs:
  prepare_dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  run_checkStyle:
      <<: *defaults
      steps:
        - attach_workspace:
            at: ~/code
        - restore_cache:
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
        - run:
            name: Run CkeckStyle
            command: ./gradlew checkstyle
  run_pmd:
      <<: *defaults
      steps:
        - attach_workspace:
            at: ~/code
        - restore_cache:
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
        - run:
            name: Run PMD
            command: ./gradlew pmd
  run_lint:
      <<: *defaults
      steps:
        - attach_workspace:
            at: ~/code
        - restore_cache:
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
        - run:
            name: Run Lint
            command: ./gradlew lint test
  run_tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          name: Run Unit Tests
          command: ./gradlew test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
  build_app:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  deploy_release:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - deploy:
          name: Deploy APK.
          command: |
              bash ./scripts/deploy-hockey.sh
              bash ./scripts/deploy-fabric.sh
workflows:
  version: 2
  build:
    jobs:
      - prepare_dependencies
      - run_tests:
          requires:
            - prepare_dependencies
      - run_checkStyle:
          requires:
            - prepare_dependencies
      - run_pmd:
          requires:
            - prepare_dependencies
      - run_lint:
          requires:
            - prepare_dependencies
      - build_app:
          requires:
            - prepare_dependencies
      - deploy_release:
          requires:
            - prepare_dependencies
            - build_app
            - run_tests
            - run_checkStyle
            - run_pmd
            - run_lint
          filters:
            branches:
              only: master
